apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ben-ingress
  namespace: sock-shop
  annotations:
   cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: sock-shop.adeyeletechhub.com.ng
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: front-end
              port:
                number: 80
      
  tls:
      - hosts:
          - sock-shop.adeyeletechhub.com.ng
        secretName: tls-secret