apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ben-ingress
  #namespace: argocd
  annotations:
   cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: argocd.adeyeletechhub.com.ng
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: argocd-server
              port:
                number: 443
      
  tls:
      - hosts:
          - argocd.adeyeletechhub.com.ng
        secretName: tls-secret